name: id_card_formatter
description: A lightweight Flutter/Dart extension to format ID numbers (Generic Formatter, NIDA, phone number, Voter ID, and NCARD card style). Also supports currency formatting and customizable generic ID formats..
version: 0.0.33
homepage: https://github.com/hemmy6894/id_card_formatter
license: MIT

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  
